[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"

[env]
PYTHONUNBUFFERED = "1"
